enable_testing ()

set (LOSS_RATE 0.1)

add_test(NAME t_udp_client_send      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucS)
add_test(NAME t_udp_server_send      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usS)
add_test(NAME t_udp_client_recv      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucR)
add_test(NAME t_udp_server_recv      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usR)
add_test(NAME t_udp_client_dupl      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucD)
add_test(NAME t_udp_server_dupl      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usD)

add_test(NAME t_ucS_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 1M -w 32K)
add_test(NAME t_ucS_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 128K -w 8K)
add_test(NAME t_ucS_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 16 -w 1)
add_test(NAME t_ucS_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 32K)
add_test(NAME t_ucR_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 1M -w 32K)
add_test(NAME t_ucR_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 128K -w 8K)
add_test(NAME t_ucR_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 16 -w 1)
add_test(NAME t_ucR_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 32K)
add_test(NAME t_ucD_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 1M -w 32K)
add_test(NAME t_ucD_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 128K -w 8K)
add_test(NAME t_ucD_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 16 -w 1)
add_test(NAME t_ucD_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 32K)

add_test(NAME t_usS_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 1M -w 32K)
add_test(NAME t_usS_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 128K -w 8K)
add_test(NAME t_usS_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 16 -w 1)
add_test(NAME t_usS_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 32K)
add_test(NAME t_usR_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 1M -w 32K)
add_test(NAME t_usR_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 128K -w 8K)
add_test(NAME t_usR_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 16 -w 1)
add_test(NAME t_usR_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 32K)
add_test(NAME t_usD_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 1M -w 32K)
add_test(NAME t_usD_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 128K -w 8K)
add_test(NAME t_usD_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 16 -w 1)
add_test(NAME t_usD_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 32K)

add_test(NAME t_ucS_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_ucS_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_ucS_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucSd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_ucR_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_ucR_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_ucR_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucRd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_ucD_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_ucD_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_ucD_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -ucDd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})

add_test(NAME t_usS_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_usS_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_usS_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usSd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_usR_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_usR_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_usR_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usRd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_usD_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_usD_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_usD_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -usDd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})

add_test(NAME t_ipv4_client_send     COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icS)
add_test(NAME t_ipv4_server_send     COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isS)
add_test(NAME t_ipv4_client_recv     COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icR)
add_test(NAME t_ipv4_server_recv     COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isR)
add_test(NAME t_ipv4_client_dupl     COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icD)
add_test(NAME t_ipv4_server_dupl     COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isD)

add_test(NAME t_icS_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 1M -w 32K)
add_test(NAME t_icS_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 128K -w 8K)
add_test(NAME t_icS_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 16 -w 1)
add_test(NAME t_icS_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 32K)
add_test(NAME t_icR_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 1M -w 32K)
add_test(NAME t_icR_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 128K -w 8K)
add_test(NAME t_icR_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 16 -w 1)
add_test(NAME t_icR_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 32K)
add_test(NAME t_icD_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 1M -w 32K)
add_test(NAME t_icD_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 128K -w 8K)
add_test(NAME t_icD_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 16 -w 1)
add_test(NAME t_icD_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 32K)

add_test(NAME t_isS_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 1M -w 32K)
add_test(NAME t_isS_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 128K -w 8K)
add_test(NAME t_isS_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 16 -w 1)
add_test(NAME t_isS_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 32K)
add_test(NAME t_isR_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 1M -w 32K)
add_test(NAME t_isR_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 128K -w 8K)
add_test(NAME t_isR_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 16 -w 1)
add_test(NAME t_isR_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 32K)
add_test(NAME t_isD_1M_32k           COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 1M -w 32K)
add_test(NAME t_isD_128K_8K          COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 128K -w 8K)
add_test(NAME t_isD_16_1             COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 16 -w 1)
add_test(NAME t_isD_32K_d            COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 32K)

add_test(NAME t_icS_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_icS_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_icS_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_icR_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_icR_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_icR_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_icD_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_icD_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_icD_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})

add_test(NAME t_isS_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_isS_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_isS_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_isR_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_isR_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_isR_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_isD_128K_8K_l        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_isD_128K_8K_L        COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_isD_128K_8K_lL       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})

add_test(NAME t_icnS_128K_8K_l       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSnd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_icnS_128K_8K_L       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSnd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_icnS_128K_8K_lL      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icSnd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_icnR_128K_8K_l       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRnd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_icnR_128K_8K_L       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRnd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_icnR_128K_8K_lL      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icRnd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_icnD_128K_8K_l       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDnd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_icnD_128K_8K_L       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDnd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_icnD_128K_8K_lL      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -icDnd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})

add_test(NAME t_isnS_128K_8K_l       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSnd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_isnS_128K_8K_L       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSnd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_isnS_128K_8K_lL      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isSnd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_isnR_128K_8K_l       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRnd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_isnR_128K_8K_L       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRnd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_isnR_128K_8K_lL      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isRnd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})
add_test(NAME t_isnD_128K_8K_l       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDnd 128K -w 8K -l ${LOSS_RATE})
add_test(NAME t_isnD_128K_8K_L       COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDnd 128K -w 8K -L ${LOSS_RATE})
add_test(NAME t_isnD_128K_8K_lL      COMMAND "${PROJECT_SOURCE_DIR}/txrx.sh" -isDnd 128K -w 8K -l ${LOSS_RATE} -L ${LOSS_RATE})

add_custom_target (check_lab4 COMMAND "${PROJECT_SOURCE_DIR}/tun.sh" check 144 145
                              COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure --timeout 10 -R "^t_"
                              COMMENT "Testing the TCP connection...")